### ISSUE TITLE
Missing dependencies in KDE desktops

### ISSUE THREAD

**Issue by tomas-teijeiro** [gentakojima/emojione-picker-ubuntu#1]
I just have tested the package in a Kubuntu 14.04 installation without unity or gnome, and it seems some dependencies are missing in the package declaration. Specifically, I had to manually install the following packages:

- gir1.2-notify-0.7
- gir1.2-appindicator3-0.1

Probably, more *gir1.2-related* packages are needed, but it seems I already have them installed. After these dependencies were met, the application worked properly.

**Comment by gentakojima** [comment]
Thanks for bringing this into attention. I'll test this properly in a virtual machine with Kubuntu 14.04 to catch all the missing dependencies.

**Comment by gentakojima** [comment]
Ok, these packages were missing from a base Kubuntu installation but not from a base Ubuntu installation. There is another dependency involved to be able to draw svg icons, but that is all: gir1.2-rsvg-2.0. This is fixed now, thanks!
