### ISSUE TITLE
Doesn't work in OpenSuse Leap 42.1 KDE

### ISSUE THREAD

**Issue by Dodoheimer** [gentakojima/emojione-picker-ubuntu#11]
Hi,

I installed the emojione-picker on Opensuse Leap 42.1 KDE. When I run the command "emojione-picker" I become this message:

Traceback (most recent call last):
  File "/usr/local/bin/emojione-picker", line 21, in <module>
    require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

Can you help me? Which package is missing?

Thanks :)

**Comment by gentakojima** [comment]
I can't download OpenSuse Leap right now because the website seems to be down, but I think installing this package should make it work: https://software.opensuse.org/package/python-appindicator

Please let me know if you can't make it to work and I'll try to download OpenSuse Leap 42.1 KDE again to test it.

**Comment by Dodoheimer** [comment]
Hi, thanks for your quick answer.

Sadly, that does not solve my problem, I already installed it.

**Comment by DPDmancul** [comment]
Gives the same error in kubuntu 16.04:
$ emojione-picker 
/usr/local/bin/emojione-picker:20: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk, GObject, Gdk, Notify, GdkPixbuf
/usr/local/bin/emojione-picker:20: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk, GObject, Gdk, Notify, GdkPixbuf
Traceback (most recent call last):
  File "/usr/local/bin/emojione-picker", line 21, in <module>
    from gi.repository import AppIndicator3 as appindicator
ImportError: cannot import name AppIndicator3

**Comment by gentakojima** [comment]
@DPDmancul you're probably using an older version. That warnings should have gone long ago. Make sure to grab the latest version.

I've just installed OpenSuse Leap 42.1 KDE and I'm looking at this right now, sorry for the delay.

**Comment by gentakojima** [comment]
@Dodoheimer it seems like the package you need is called **typelib-1_0-AppIndicator3-0_1**

Don't want to be rude, but that's the most inconsistent naming scheme I've seen... well, recently at least.

@DPDmancul if you are on *Ubuntu, you need to install **gir1.2-appindicator3-0.1** (it's specified in the README)

Yep, the name is not much better in Ubuntu either.

Please, if you can check it again and report. Thanks.

**Comment by Dodoheimer** [comment]
@gentakojima Thank you very much for investigating the issue. I found this package and now it works :)  And yes, this naming sheme is really... interesting....

**Comment by Dodoheimer** [comment]
@DPDmancul I accidentally closes the issue, but reopened it because you have also a problem. Hope the suggestion help you with your problem.

**Comment by DPDmancul** [comment]
Installing the new version it works! thanks
