### ISSUE TITLE
should not stay open forever

### ISSUE THREAD

**Issue by azerafati** [gentakojima/emojione-picker-ubuntu#13]
It's very useful to me but I don't want to keep it always open,  I want to open it when I need it and close it after that. I'm on low memory

**Comment by gentakojima** [comment]
Sorry for the delay.

I've added an "Exit" option, and I've also added a .desktop entry to be able to open it from the Dash.

This works if installed using the own built Debian package (method 2). The standalone distro-independent installer (method 3) is still untested, but should also work.
