### ISSUE TITLE
EmojiOne added Unicode 9.0 graphics

### ISSUE THREAD

**Issue by eosrei** [gentakojima/emojione-picker-ubuntu#14]
I added Unicode 9.0 to https://github.com/eosrei/emojione-color-font but I can't select the new ones 😢😉

![Unicode 9.0!](https://cloud.githubusercontent.com/assets/195061/15986784/31a3ae8a-2fc6-11e6-8f25-e7c8f003cf2d.png)

**Comment by gentakojima** [comment]
Thanks for pointing this!

I've just updated to EmojiOne 2.2, the update of Q2 2016, which brings some new emojis and updates a lot of them. But it's still missing all of the emojis from 9.0. 

I expect them to be added soon to EmojiOne, and since I'm 100% relying on emoji data from EmojiOne, I'm locked up here. I'll keep this opened at least until the Q3 2016 update, which probably will fix this.

**Comment by eosrei** [comment]
They aren't all in the JSON file, but *all* of the UC9 graphics are in V2.2.2. I only use the graphics, but if you need the JSON then, yes, you need to wait until the next release. Check this page with my font loaded: http://emojipedia.org/unicode-9.0/ Everything works.

**Comment by gentakojima** [comment]
Oh, you're right. I've even uploaded them, but they're not in the json. It seems they are unannounced for now, though. Thanks again, @eosrei!

**Comment by gentakojima** [comment]
There is now an official "Unicode 9" update. However, new emojis are defined in a separated category by now (see [this issue](https://github.com/Ranks/emojione/issues/276)). 

I've updated emoji.json, but I had to add the category "Unicode 9" to the picker. I still won't close this until this unicode 9 category thing is handled properly.

**Comment by gentakojima** [comment]
A later update properly categorized the unicode 9 emojis, and I've just updated the picker to reflect this. I think this can now be closed.

**Comment by mauromol** [comment]
Am I wrong or the official Ubuntu PPA does not include this update? For example, I can't find the nauseated emoticon anywhere: https://emojipedia.org/nauseated-face/
