### ISSUE TITLE
The application fills the full screen, not allowing back-navigation

### ISSUE THREAD

**Issue by tomas-teijeiro** [gentakojima/emojione-picker-ubuntu#2]
When I select a category with a large number of emojis (for example the *People* or *Flags* categories), the list of emojis fills the full screen, not allowing to see any other thing nor going back in the selection, forcing to pick one emoji to move forward (or press Esc, of course). I think this is a usability issue that could be improved. I attach a full-screen snapshot of what happens when I hover the *People* category.

![n1001](https://cloud.githubusercontent.com/assets/4498106/12697503/fce3d006-c785-11e5-975b-c93794879197.png)

**Comment by gentakojima** [comment]
Thanks for the report. The emoji data from emojione only categorizes the emojis in these 8 basic groups, corresponding with the usual grouping in Android/ios emoji keyboards.

I'm working in a grouping feature, manually picking icon groups inside each category. For example, Families (containing the 15 family variants), and Clothing (containing more than 30 clothing articles and complements). Once I get there, we can evaluate again if further action is needed.

Unfortunately, Ubuntu and Gnome App Indicator implementation only supports basic menu items (optionally with icons, checkmarks...) so I can't put an icon grid in there.

I'll report here advances in this matter.

**Comment by gentakojima** [comment]
I implemented these changes in 2673a128a14f956cf7036d1eace6d3976b3d4157. Toned and untoned emojis are also properly grouped together now. 

Groups are defined in assets/groups.json. References in that file are to unicode codes and not name codes, which is a bit slower runtime (not appreciable), but more maintenable in case emojione changes or tweaks these names.

Tone related icons always have an equivalent non-toned icon and they are discovered automatically, so there is no need to put them in that file.

Grouping still probably needs some work. Category separation seems non-sensical enough for me in some cases, so further grouping doesn't help. Also, the Flags category is still untouched. I don't know if I should group them by contintents or alphabetically. Also, after Zimbabwe, some non-country flags are following and they should probably have their own group "Misc" or similar.

**Comment by gentakojima** [comment]
Can you try the current version? Maybe grouping needs more work, but I think it should be far more usable now on KDE.

**Comment by tomas-teijeiro** [comment]
The problem of how the list of item is displayed is still there, but I assume this is a problem of the implementation in Plasma. With the new grouping the application is much more usable now, thank you!!
