### ISSUE TITLE
Icons appear huge

### ISSUE THREAD

**Issue by uriel1998** [gentakojima/emojione-picker-ubuntu#4]
So to answer one question, yes, the app works just fine in the system tray of Debian Jessie using Openbox as the DE.  Functionality is great, and I'm really digging it.

The one problem I'm having is that unlike your screenshot, where the SVG icons are a reasonable size, they show up at ~128px on my system.  Not a deal-killer, but obnoxious. I know just enough to be dangerous, not enough to figure out where the size is dictated. Any thoughts?

![2016-02-16--1455639740_1366x768_scrot](https://cloud.githubusercontent.com/assets/1130750/13082719/e13939e6-d49f-11e5-8dc5-22a2aeb85a3d.png)

**Comment by gentakojima** [comment]
Thanks for taking your time to report this issue and your kind words.

Are you are using Stalonetray with Openbox? I've seen this behaviour thanks to #3, and it seems this also happens in the Gnome desktop. Meddling with Stalonetray options don't seem to help.

I'll take a look into this and try to fix as soon as possible, but I'm unsure what's wrong at this very moment.

**Comment by gentakojima** [comment]
Please, test commit #63b215b. I think these changes might have fixed this issue.

**Comment by uriel1998** [comment]
Just tested; works fine for main body of emoji.  Recent ones are still the large size.  📡

**Comment by gentakojima** [comment]
Oops. I must have missed something, but I'm glad the solution worked. Will fix it tonight.

**Comment by gentakojima** [comment]
Ok, this should be fixed in commit 2428e08. I'm closing this now, if the problem persists please reopen it. Thanks for your help!

**Comment by uriel1998** [comment]
It's working great now. (And tint2 with Openbox on Debian Jessie, FWIW.)
