### ISSUE TITLE
Methods 2 and 3 fail with bad dependencies

### ISSUE THREAD

**Issue by thor314** [gentakojima/emojione-picker-ubuntu#49]
Filing several issues, one per method that failed. OS: Ubuntu
Method 2,3 fails with error:
E: Unable to locate package python-2.7
and
E: Unable to locate package python-notify

Resolves if python-2.7 is changed to `python`.

`debuild` is not a recognized command.

defaulting to method 3, running the install script resolved to error:
```
    from gi import require_version
ImportError: No module named gi
```

**Comment by tteskac** [comment]
I was able to solve it for **method 3** by installing python2 gi module using:
`sudo apt install python-gi`

**Comment by novoid** [comment]
I can confirm that `sudo apt install python-gi` solves the issue on current Xubuntu 20.04 LTS.
