### ISSUE TITLE
Just wanted to say thanks :)

### ISSUE THREAD

**Issue by vooze** [gentakojima/emojione-picker-ubuntu#7]
It works great so far :) next step is to get color emojies in ubuntu natively, but I guess they are working on that for 16.10 (unity 8)

**Comment by gentakojima** [comment]
Thanks, please don't hesitate to send any problem you may have with this in a new issue.

I don't know about that. It seems there is a colored TTF format supported on Windows 8+, but they won't work on Linux. I heard Qt guys were working on supporting this, but if this is being done at graphical tookit level, it must be done also by Gtk to support to be more complete.

I will continue working on the picker, probably will try to do something more sophisticated than this at some point.
